controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_controller:
      type: ackermann_steering_controller/AckermannSteeringController

ackermann_controller:
  ros__parameters:
    front_steering_joints: ["front_left_steer_joint", "front_right_steer_joint"]
    front_wheels_joints: ["front_left_wheel_joint", "front_right_wheel_joint"]
    rear_wheels_joints: ["rear_left_wheel_joint", "rear_right_wheel_joint"]
    
    wheel_base: 0.3  # Distance between front and rear wheels
    wheel_track: 0.26  # Distance between left and right wheels
    wheel_radius: 0.05
    
    cmd_vel_timeout: 0.5
    base_frame_id: chassis
    
    publish_rate: 50.0
    odom_frame_id: odom
    enable_odom_tf: true
    
    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0  # m/s
        has_acceleration_limits: true
        max_acceleration: 1.0  # m/s^2
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0  # rad/s
        has_acceleration_limits: true
        max_acceleration: 1.0  # rad/s^2
        
    # PID gains for velocity control
    velocity_controller:
      p: 1.0
      i: 0.0
      d: 0.0
      
    # PID gains for steering control
    steering_controller:
      p: 1.0
      i: 0.0
      d: 0.0 